### ISSUE TITLE
Release code to this repo

### ISSUE THREAD

**Issue by raphaelmerx** [BaohaoLiao/multiback#1]
Hello, could you release your code and models as described in the ACL Anthology paper? https://aclanthology.org/2021.wmt-1.50/

The paper says the code and models "are available" at this repository, but currently it only has a README

**Comment by BaohaoLiao** [comment]
Really sorry for the delay, since I focused on EMNLP submission last week. I just upload the processing and training scripts. Feel free to ask for the things you want.

**Comment by raphaelmerx** [comment]
Thank you, appreciate it!
